apiVersion: v1
kind: Service
metadata:
  annotations:
    com.centurylinklabs.watchtower.scope: azuracast
  creationTimestamp: null
  labels:
    io.kompose.service: azuracast
  name: azuracast
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "2022"
      port: 2022
      targetPort: 2022
    - name: "3306"
      port: 3306
      targetPort: 3306
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: azuracast
status:
  loadBalancer: {}
